---
- name: Playbook that sends HTTP GET to target URI
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    urltolookup: "https://statsapi.web.nhl.com/api/v1/teams"
  tasks:
    - name: Lookup API with uri module
      ansible.builtin.uri:     # standard library - interact with APIs
        url: "{{ urltolookup }}"
        method: GET        # method to send with HTTP
      register: results    # save the JSON sent back by our script
    - name: Print out the keys within the returned JSON
      ansible.builtin.debug:
        var: results.get('json')
